# Test your FastAPI endpoints
###
GET http://127.0.0.1:8000/site_report/create/?lat=13.011026921074786&lng=77.55473637957641&name=orion mall&travel_mode=driving&cost_type=buffer&cost=500&report_id=4d83c559-fa5a-4c9d-98a3-1bafc546e0fb
Accept: application/json


###
GET http://127.0.0.1:8000/site_report/create/?lat=13.0009569&lng=77.6325712&name=Orion Avenue&travel_mode=driving&cost_type=time&cost=15
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/create/?lat=12.969693199052141&lng=77.6307545633031&name=Cambridge Layout&travel_mode=driving&cost_type=distance&cost=2500
Accept: application/json


###
GET http://127.0.0.1:8000/site_report/create/?lat=13.095999774716756&lng=77.57916090477161&name=Yelanhanka New Town&travel_mode=driving&cost_type=distance&cost=2500
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/create/?lat=13.0552603&lng=77.7638939&name=Orion Uptown&travel_mode=driving&cost_type=buffer&cost=500
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/create/?lat=12.906501&lng=77.592581&name=Cultfit&travel_mode=driving&cost_type=buffer&cost=1000
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/create/?lat=13.063665&lng=77.586943&name=Cultfit&travel_mode=driving&cost_type=buffer&cost=1000
Accept: application/json


###
GET http://127.0.0.1:8000/site_report/40b37f44-ff12-481a-b962-7b7b203026e2/130631_776205/cft
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/40b37f44-ff12-481a-b962-7b7b203026e2/130631_776205/shopping_mall
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/2f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/population
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/1f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/population
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/1f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/companies/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/2f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/demand_generator/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/2f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/projects/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/5fca8372-db67-4e32-9c34-17818bca7c19/130552_777638/affluence
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/2f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/income
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/c72e8b10-34f9-46d5-94ed-bf54976b7b8b/129696_776307/competition/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/top_brands/500_catchment
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/1f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/category_count/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/ed374c4c-6dc3-473b-867e-ff707e347939/130552_777638/property_price/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/2f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/medical
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/2f78f3ac-d799-470b-9738-2c4da5053cee/cf7eb825-a703-4b10-abea-066546376aa8/high_street
Accept: application/json


###
GET http://127.0.0.1:8000/site_report/initial_data/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/1f78f3ac-d799-470b-9738-2c4da5053cee/130110_775547/secondary_data/
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/initial_data/?lat=13.063665&lng=77.586943&name=Cultfit&travel_mode=driving&cost_type=time&cost=15&primary_comp=['bata','zudio']&anchor_comp=['dominos','mcdonalds']
Accept: application/json

###
GET http://127.0.0.1:8000/site_report/secondary_data/?lat=13.063665&lng=77.586943&name=Cultfit&travel_mode=driving&cost_type=time&cost=15&primary_comp=['bata','zudio']&anchor_comp=['dominos','mcdonalds']&weights={"competitor_index": 0.2, "affluence_index": 0.19, "apartments_index": 0.19, "fashion_index": 0.19, "vibrancy": 0.14, "healthcare_index": 0.1, "company_index": 0.1, "malls_index": 0.05, "supermarket_index": 0.04}
Accept: application/json